name: Build ShellCheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello:
    name: hello!
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
      - name: Download released earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: pre docker login1
        run: echo "${{ secrets.DOCKERHUB_USERNAME }}" | base64
      - name: pre docker login2
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | sha1sum
      - name: docker login
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: done
        run: echo DONE
