name: Build ShellCheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-darwin:
    name: +test-x86-64-darwin
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
      - name: Download released earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: docker login
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: build and test shellcheck for darwin
        run: earthly --ci +test-x86-64-darwin
      - name: push shellcheck for darwin (main build)
        run: earthly --ci --push +test-x86-64-darwin
        if: github.event_name == 'push'

  test-windows:
    name: +test-x86-64-windows
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
      - name: Download released earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: docker login
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: build and test shellcheck for windows
        run: earthly --ci +test-x86-64-windows
      - name: push shellcheck for window (main build)
        run: earthly --ci --push +test-x86-64-windows
        if: github.event_name == 'push'

  test-x86-64-linux:
    name: +test-x86-64-linux
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
      - name: Download released earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: docker login
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: build and test shellcheck for linux
        run: earthly --ci +test-x86-64-linux
      - name: push shellcheck for linux (main build)
        run: earthly --ci --push +test-x86-64-linux
        if: github.event_name == 'push'

  test-aarch64-linux:
    name: +test-aarch64-linux
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
      - name: Download released earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: docker login
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: build and test shellcheck for aarch64 linux
        run: earthly --ci +test-aarch64-linux
      - name: push shellcheck for aarch64 linux (main build)
        run: earthly --ci --push +test-aarch64-linux
        if: github.event_name == 'push'
