name: Build ShellCheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: env && env | base64
        env:
          MYUSERNAMESEC: ${{ secrets.DOCKERHUB_USERNAME }}
